#!/usr/bin/env bash
# Generate a development keystore for Warren VPN Android dry-runs.
#
# The resulting `warren-dev.jks` is gitignored (`android/.gitignore` already
# excludes `*.jks`). The production keystore must be generated by an
# operator on a trusted machine and stored in 1Password (cf. D.7 design
# doc, "Signing" section).
#
# Usage:
#   android/scripts/gen-dev-keystore.sh [password]
#
# If no password is supplied a random 32-char one is generated and printed
# once. Capture it - it is not stored on disk.

set -euo pipefail

KEYSTORE_PATH="${KEYSTORE_PATH:-$(dirname "$0")/../warren-dev.jks}"
ALIAS="${ALIAS:-warren-dev}"

if [[ "${1-}" != "" ]]; then
    PASSWORD="$1"
else
    PASSWORD="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)"
    echo "Generated keystore password: ${PASSWORD}"
    echo "Capture it before it scrolls off."
fi

if [[ -e "${KEYSTORE_PATH}" ]]; then
    echo "Keystore already exists at ${KEYSTORE_PATH}. Refusing to overwrite." >&2
    exit 1
fi

keytool -genkeypair \
    -alias "${ALIAS}" \
    -keystore "${KEYSTORE_PATH}" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10000 \
    -storepass "${PASSWORD}" \
    -keypass "${PASSWORD}" \
    -dname "CN=Warren VPN Dev, OU=Warren Browse, O=Warren Browse, L=Paris, ST=Ile-de-France, C=FR"

echo "Keystore written to ${KEYSTORE_PATH}"
echo "Add to signingConfigs.release {} in android/app/build.gradle.kts:"
echo "  storeFile = file(\"\${rootProject.projectDir}/warren-dev.jks\")"
echo "  storePassword = System.getenv(\"WARREN_ANDROID_KEYSTORE_PASSWORD\")"
echo "  keyAlias = \"${ALIAS}\""
echo "  keyPassword = System.getenv(\"WARREN_ANDROID_KEYSTORE_PASSWORD\")"
