#!/usr/bin/env python3
"""Derive the non-prod status-bar drawables from the prod ones.

The ongoing tunnel notification, the forum notification and the quick-settings
tile all draw the bare Warren mark. A device carrying both installs would show
two identical icons with nothing to say which product holds the tunnel, so the
non-prod flavors overlay the same drawable with the beta pip stamped on it.

Android flattens a notification small icon to an alpha mask and tints it to the
system foreground, so the amber does not survive there: the marker is the `B`
knocked out of the pip. The pip geometry and the letter come from
graphics/make-beta-icon.py, the same producer as the app icon's badge, so the
two cannot drift apart. The desktop tray takes a different route because its
coloured variant is the one users see by default: it recolours the lock rather
than badging it (graphics/menubar-beta-palette.txt).

The overlay has to land in an unqualified `drawable/` directory: a
`drawable-nodpi/` copy is a different resource configuration, which Android
would add alongside the library's default rather than replace it.

Writes android/app/src/{beta,staging}/res/drawable/small_logo_{white,black}.xml.
Run it after any redraw of the mark or of the BETA wordmark; the JVM test
BetaSmallLogoOverrideTest goes red when the overlay no longer carries the mark.
"""

import importlib
import pathlib
import re
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
ANDROID_DIR = SCRIPT_DIR.parent
GRAPHICS_DIR = ANDROID_DIR.parent / 'graphics'

sys.path.insert(0, str(GRAPHICS_DIR))
beta_icon = importlib.import_module('make-beta-icon')

PROD_DRAWABLE_DIR = ANDROID_DIR / 'lib/ui/resource/src/main/res/drawable'
DRAWABLES = ('small_logo_white', 'small_logo_black')
BADGED_FLAVORS = ('beta', 'staging')

AMBER = '#CA963C'
# The pip covers 3/8 of the icon edge, the proportion generate-menubar-icons.sh
# stamps on the desktop tray. The drawable declares 24dp, above the 20px floor
# under which that script drops the letter, so the B is always drawn here.
PIP_NUMERATOR = 3
PIP_DENOMINATOR = 8
# The mark is scaled down and pushed to the opposite corner rather than left at
# full size and clipped. The Warren mark is two ears that reach into every
# corner, so a pip stamped over one of them cuts an ear off at the pip's edge
# and the result reads as a broken logo, not a badged one. Shrinking costs a
# little presence and keeps the mark whole.
MARK_SCALE = 0.76
# Transparent gap between the pip and the mark, in viewport units, so the two
# shapes stay separate once the status bar flattens them to a single tint.
PIP_HALO = 3.0

# Absolute path commands and how many numbers each takes. Relative commands and
# arcs never appear in the wordmark, and transforming them needs the current
# point, so the parser refuses them rather than emitting a smudge.
PATH_PARAMETERS = {'M': 2, 'L': 2, 'T': 2, 'Q': 4, 'S': 4, 'C': 6, 'H': 1, 'V': 1, 'Z': 0}
COMMAND = re.compile(r'([A-Za-z])([^A-Za-z]*)')
NUMBER = re.compile(r'-?\d*\.?\d+(?:[eE][-+]?\d+)?')

HEADER = """<!-- Generated by android/scripts/generate-beta-small-logo.py, do not edit by hand.

     The non-prod overlay of the prod status-bar mark: the same artwork, scaled
     down towards the opposite corner, with the amber beta pip in the freed
     bottom-left one, so a device carrying both installs can tell which product
     is holding the tunnel. The status bar flattens this to an alpha mask and
     tints it, where colour cannot survive, so the marker is the B knocked out
     of the pip. The corner is forced: the forum-activity dot is an amber circle
     at the bottom right.

     The mark is also clipped out of the pip, one halo wider than the pip
     itself. The clip keeps the letter a hole through the whole icon, since an
     ear crossing the pip would fill the counters of the B back in once the icon
     is a single tint, and the halo keeps the two shapes visibly separate
     instead of fused along their shared edge. -->
"""


def viewport(vector_xml: str) -> float:
    match = re.search(r'android:viewportWidth="([\d.]+)"', vector_xml)
    if not match:
        sys.exit('the prod drawable declares no viewportWidth')
    return float(match.group(1))


def transform_path(path_data: str, scale: float, offset_x: float, offset_y: float) -> str:
    """Rewrites an absolute path into the pip's coordinate space."""
    out = []
    for command, body in COMMAND.findall(path_data):
        if command.upper() not in PATH_PARAMETERS:
            sys.exit(f'unsupported path command {command!r} in the wordmark')
        if command.islower():
            sys.exit(f'relative path command {command!r} in the wordmark, cannot transform it')
        arity = PATH_PARAMETERS[command]
        numbers = [float(value) for value in NUMBER.findall(body)]
        if arity == 0:
            out.append(command)
            continue
        if not numbers or len(numbers) % arity:
            sys.exit(f'{command} takes {arity} numbers, found {len(numbers)}')
        # A repeated group after M is an implicit L, and after any other command
        # it repeats that command; both keep the same parameter layout.
        for start in range(0, len(numbers), arity):
            group = numbers[start:start + arity]
            if command == 'H':
                moved = [group[0] * scale + offset_x]
            elif command == 'V':
                moved = [group[0] * scale + offset_y]
            else:
                moved = [
                    value * scale + (offset_x if index % 2 == 0 else offset_y)
                    for index, value in enumerate(group)
                ]
            out.append(command + ' '.join(number(value) for value in moved))
    return ''.join(out)


def number(value: float) -> str:
    return f'{value:.4f}'.rstrip('0').rstrip('.')


def rounded_square(size: float, radius: float, origin_x: float, origin_y: float) -> str:
    far_x = number(origin_x + size)
    far_y = number(origin_y + size)
    near_x = number(origin_x + radius)
    near_y = number(origin_y + radius)
    inner_x = number(origin_x + size - radius)
    inner_y = number(origin_y + size - radius)
    left = number(origin_x)
    top = number(origin_y)
    near = number(radius)
    arc = f'A{near},{near} 0 0,1 '
    return (
        f'M{near_x},{top}'
        f'H{inner_x}{arc}{far_x},{near_y}'
        f'V{inner_y}{arc}{inner_x},{far_y}'
        f'H{near_x}{arc}{left},{inner_y}'
        f'V{near_y}{arc}{near_x},{top}'
        'Z'
    )


def pip_size(canvas: float) -> float:
    return canvas * PIP_NUMERATOR / PIP_DENOMINATOR


def pip_origin(canvas: float) -> tuple:
    """Bottom-left, the corner the forum-activity dot never uses."""
    return (0.0, canvas - pip_size(canvas))


def pip_square(canvas: float, grow: float = 0.0) -> str:
    size = pip_size(canvas) + grow
    origin_x, origin_y = pip_origin(canvas)
    radius = size * beta_icon.PIP_CORNER_RADIUS / beta_icon.PIP_CANVAS
    return rounded_square(size, radius, origin_x, origin_y - grow)


def pip_path(canvas: float, letter: str) -> str:
    """The pip: the rounded square with the B as a second, enclosed subpath."""
    size = pip_size(canvas)
    origin_x, origin_y = pip_origin(canvas)
    x_min, y_min, x_max, y_max = beta_icon.B_GLYPH_BOX
    scale = (size * beta_icon.PIP_LABEL_HEIGHT / beta_icon.PIP_CANVAS) / (y_max - y_min)
    offset_x = origin_x + size / 2 - scale * (x_min + x_max) / 2
    offset_y = origin_y + size / 2 - scale * (y_min + y_max) / 2
    return pip_square(canvas) + transform_path(letter, scale, offset_x, offset_y)


def mark_clip(canvas: float) -> str:
    """The whole canvas minus the pip, so the mark cannot fill the letter in."""
    edge = number(canvas)
    return f'M0,0H{edge}V{edge}H0Z' + pip_square(canvas, PIP_HALO)


def badge(prod_xml: str, letter: str) -> str:
    body = prod_xml[prod_xml.index('<vector'):]
    canvas = viewport(body)
    open_end = body.index('>') + 1
    closing = body.rindex('</vector>')
    inset = number(canvas * (1 - MARK_SCALE))
    clip = (
        '    <group>\n'
        '        <clip-path\n'
        f'            android:pathData="{mark_clip(canvas)}"\n'
        '            android:fillType="evenOdd" />\n'
        '        <group\n'
        f'            android:translateX="{inset}"\n'
        f'            android:scaleX="{number(MARK_SCALE)}"\n'
        f'            android:scaleY="{number(MARK_SCALE)}">\n'
    )
    # Painted after the mark so the pip sits above it, and even-odd so the
    # letter is a hole rather than a second amber shape that tinting swallows.
    pip = (
        '    <path\n'
        f'        android:pathData="{pip_path(canvas, letter)}"\n'
        f'        android:fillColor="{AMBER}"\n'
        '        android:fillType="evenOdd" />\n'
    )
    return (
        HEADER
        + body[:open_end]
        + '\n'
        + clip
        + body[open_end:closing]
        + '        </group>\n'
        + '    </group>\n'
        + pip
        + body[closing:]
    )


def main() -> None:
    letter = beta_icon.beta_letter_path((GRAPHICS_DIR / 'beta-badge.svg').read_text())
    for name in DRAWABLES:
        badged = badge((PROD_DRAWABLE_DIR / f'{name}.xml').read_text(), letter)
        for flavor in BADGED_FLAVORS:
            target = ANDROID_DIR / 'app/src' / flavor / 'res/drawable' / f'{name}.xml'
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(badged)
            print(f'wrote {target.relative_to(ANDROID_DIR.parent)}')


if __name__ == '__main__':
    main()
