//! Interface with macOS-specific bits.

#![deny(missing_docs)]
#![cfg(target_os = "macos")]

/// Processes
pub mod process;

/// The code signature of the running program
pub mod code_signing;

/// OS bindings generated by 'generate_bindings.rs'
#[expect(non_camel_case_types, clippy::allow_attributes)]
mod bindings;

/// Networking utilities
pub mod net;
