#!/usr/bin/env ruby
# frozen_string_literal: true

# Drop genuinely-dead Mullvad-era Swift files from BOTH the Xcode project
# (project.pbxproj) AND from disk. poka explicitly approved deleting these
# from disk, overriding the team's usual keep-on-disk convention.
#
# Every file below was verified to be dead before inclusion:
#   (a) it exists on disk,
#   (b) it has zero "in Sources" build-file entries (compiled by no target),
#       with the single deliberate exception of StoreTransactionLog.swift (see
#       below), and
#   (c) the type(s) it defines have zero references from compiled code (only
#       comments, other dead files, or a distinct live duplicate reference
#       them).
#
# Clusters dropped:
#   1. Legacy Mullvad actor: PacketTunnelActor + its satellites,
#      ProtocolObfuscator, EventChannel. Replaced by WarrenQuinnActor.
#   2. Ephemeral-peer / PostQuantum FFI: EphemeralPeerExchangeActor,
#      EphemeralPeerNegotiator, both EphemeralPeerReceiver.swift files (the
#      WarrenRustRuntime @_cdecl callback and the WarrenTypes class),
#      TunnelObfuscator (live no-op replacement is TunnelObfuscationTypes.swift),
#      and the PacketTunnel/PostQuantum exchangers.
#   3. Dead test mocks / tests referencing the above.
#   4. Dead WarrenVPN settings / payment helpers.
#   5. StoreTransactionLog.swift: dead, never referenced. Live dedup is an
#      in-memory set. UNLIKE the rest it still has one "in Sources" entry in
#      the WarrenVPN app target, so the script removes that build-file entry
#      too. Nothing in compiled code references the StoreTransactionLog type.
#   6. The stray 0-byte relays-prebuild.log (build-script output, not a project
#      file reference: deleted from disk only).
#
# KEPT (do NOT touch): PacketTunnelActorProtocol.swift, PacketTunnelActorStub.swift,
# WarrenQuinnActor.swift, GotaTunActor.swift, EphemeralPeerReceiving.swift,
# WireGuardKey.swift, TunnelObfuscationTypes.swift.
#
# Idempotent: re-running once files are gone is a no-op.

require "xcodeproj"

SCRIPT_DIR = File.dirname(File.expand_path(__FILE__))
PROJECT_PATH = File.join(SCRIPT_DIR, "WarrenVPN.xcodeproj")

# Project-relative paths so duplicate basenames (two EphemeralPeerReceiver.swift)
# are matched unambiguously against each fileRef's real_path. NOTE: explicit
# string array, not %w[], because one path ("View controllers") contains a space.
DEAD_FILES = [
  "PacketTunnelCore/Actor/PacketTunnelActor.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+ConnectionMonitoring.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+Public.swift",
  "PacketTunnelCore/Actor/PacketTunnelActor+SleepCycle.swift",
  "PacketTunnelCore/Actor/PacketTunnelActorReducer.swift",
  "PacketTunnelCore/Actor/PacketTunnelActorCommand.swift",
  "PacketTunnelCore/Actor/ProtocolObfuscator.swift",
  "PacketTunnelCore/Actor/EventChannel.swift",
  "WarrenRustRuntime/EphemeralPeerExchangeActor.swift",
  "WarrenRustRuntime/EphemeralPeerNegotiator.swift",
  "WarrenRustRuntime/EphemeralPeerReceiver.swift",
  "WarrenRustRuntime/TunnelObfuscator.swift",
  "WarrenTypes/Protocols/EphemeralPeerReceiver.swift",
  "PacketTunnel/PostQuantum/PostQuantumKeyExchangeActor.swift",
  "PacketTunnel/PostQuantum/EphemeralPeerExchangingPipeline.swift",
  "PacketTunnel/PostQuantum/MultiHopEphemeralPeerExchanger.swift",
  "PacketTunnel/PostQuantum/SingleHopEphemeralPeerExchanger.swift",
  "PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift",
  "PacketTunnelCoreTests/Mocks/EphemeralPeerExchangeActorStub.swift",
  "PacketTunnelCoreTests/PacketTunnelActorTests.swift",
  "PacketTunnelCoreTests/EphemeralPeerExchangingPipelineTests.swift",
  "PacketTunnelCoreTests/MultiHopEphemeralPeerExchangerTests.swift",
  "PacketTunnelCoreTests/SingleHopEphemeralPeerExchangerTests.swift",
  "WarrenRustRuntimeTests/EphemeralPeerExchangeActorTests.swift",
  "WarrenRustRuntimeTests/TunnelObfuscationTests.swift",
  "WarrenVPN/Coordinators/Settings/SettingsValidationErrorContentView.swift",
  "WarrenVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift",
  "WarrenVPN/View controllers/Settings/SettingsPromptAlertItem.swift",
  "WarrenVPN/Extensions/RESTCreateApplePaymentResponse+Localization.swift",
  "WarrenVPN/StorePaymentManager/StoreTransactionLog.swift",
].freeze

# Disk-only artifacts: present on disk, no PBXFileReference. Deleted from disk,
# never touched in the project. relays-prebuild.log is regenerated by the
# checkRelays build phase, so removing the stale 0-byte file is harmless.
DISK_ONLY = %w[
  relays-prebuild.log
].freeze

project = Xcodeproj::Project.open(PROJECT_PATH)
project_root = File.expand_path(SCRIPT_DIR)

removed_build_files = []
removed_file_refs = []
deleted_from_disk = []

DEAD_FILES.each do |rel_path|
  abs_path = File.join(project_root, rel_path)

  # Match every fileRef whose resolved real_path is exactly this file.
  refs = project.files.select { |f| f.real_path.to_s == abs_path }

  refs.each do |file_ref|
    # Remove any build-file entries (Sources or otherwise) across all targets.
    project.targets.each do |target|
      next unless target.respond_to?(:source_build_phase)

      [target.source_build_phase, target.respond_to?(:resources_build_phase) ? target.resources_build_phase : nil].compact.each do |phase|
        phase.files.select { |bf| bf.file_ref == file_ref }.each do |bf|
          phase.remove_build_file(bf)
          removed_build_files << "#{rel_path} from #{target.name}"
        end
      end
    end

    # Remove the file reference from its group, then dispose it.
    file_ref.remove_from_project
    removed_file_refs << rel_path
  end

  # Delete from disk.
  if File.exist?(abs_path)
    File.delete(abs_path)
    deleted_from_disk << rel_path
  end
end

DISK_ONLY.each do |rel_path|
  abs_path = File.join(project_root, rel_path)
  next unless File.exist?(abs_path)

  File.delete(abs_path)
  deleted_from_disk << rel_path
end

if removed_build_files.empty? && removed_file_refs.empty? && deleted_from_disk.empty?
  puts "Nothing to do: all dead files already absent from project and disk."
else
  project.save

  unless removed_build_files.empty?
    puts "Removed #{removed_build_files.size} build-file entry/entries:"
    removed_build_files.each { |d| puts "  - #{d}" }
  end

  unless removed_file_refs.empty?
    puts "Removed #{removed_file_refs.size} file reference(s) from the project:"
    removed_file_refs.each { |d| puts "  - #{d}" }
  end

  unless deleted_from_disk.empty?
    puts "Deleted #{deleted_from_disk.size} file(s) from disk:"
    deleted_from_disk.each { |d| puts "  - #{d}" }
  end
end
