#!/usr/bin/env bash
set -eu

chmod u+s "/usr/bin/warren-exclude"
ln -sf /opt/Warren\ VPN/resources/warren-problem-report /usr/bin/warren-problem-report

systemctl enable "/usr/lib/systemd/system/warren-daemon.service"
systemctl start warren-daemon.service || echo "Failed to start warren-daemon.service"
systemctl enable "/usr/lib/systemd/system/warren-early-boot-blocking.service"
