import {
  ApiAccessMethodSettings,
  IRelaySettingsNormal,
  ISettings,
  NatPmpProto,
  ObfuscationType,
  Ownership,
} from '../shared/daemon-rpc-types';

export function getDefaultRelaySettingsNormal(): IRelaySettingsNormal {
  return {
    location: 'any',
    providers: [],
    ownership: Ownership.any,
    wireguardConstraints: {
      ipVersion: 'any',
      useMultihop: false,
      entryLocation: 'any',
    },
  };
}

export function getDefaultSettings(): ISettings {
  return {
    allowLan: false,
    autoConnect: false,
    lockdownMode: false,
    showBetaReleases: false,
    splitTunnel: {
      enableExclusions: true,
      appsList: [],
    },
    relaySettings: {
      normal: getDefaultRelaySettingsNormal(),
    },
    tunnelOptions: {
      enableIpv6: false,
      mtu: undefined,
      quantumResistant: true,
      daita: {
        enabled: false,
        directOnly: false,
      },
      dns: {
        state: 'default',
        allowExternalDns: false,
        defaultOptions: {
          blockAds: false,
          blockTrackers: false,
          blockMalware: false,
          blockAdultContent: false,
          blockGambling: false,
          blockSocialMedia: false,
        },
        customOptions: {
          addresses: [],
        },
      },
    },
    obfuscationSettings: {
      selectedObfuscation: ObfuscationType.auto,
      udp2tcpSettings: {
        port: 'any',
      },
      shadowsocksSettings: {
        port: 'any',
      },
      lwoSettings: {
        port: 'any',
      },
    },
    customLists: [],
    apiAccessMethods: getDefaultApiAccessMethods(),
    relayOverrides: [],
    recents: [],
    // `undefined` = unset, fallback to Mullvad upstream backend.
    warrenApiUrl: undefined,
    // Default OFF per doctrine `warren_multihop_doctrine_v1`.
    warrenMultiHop: {
      enabled: false,
      entryCountry: '',
      exitCountry: '',
      hpkeEpochRotationMs: 4 * 60 * 60 * 1000,
    },
    // Advanced custom-exit override OFF by default (roster selection).
    warrenCustomExit: {
      enabled: false,
      endpoint: '',
      pubkeyHex: '',
      coverDomain: undefined,
      label: '',
    },
    // NAT-PMP port-forwarding OFF by default. UDP / 1 h lifetime
    // baseline; the user toggles ON from the port-forwarding view.
    warrenNatPmp: {
      enabled: false,
      lifetimeSecs: 3600,
      rules: [],
      protocol: NatPmpProto.udp,
      suggestedExternalPort: 0,
      internalPort: 0,
    },
  };
}

export function getDefaultApiAccessMethods(): ApiAccessMethodSettings {
  // 'id's are UUIDs generated by the daemon when an access method is created,
  // and as such we can't provide a good default value for them.
  return {
    direct: {
      id: '',
      name: 'Direct',
      enabled: true,
      type: 'direct',
    },
    mullvadBridges: {
      id: '',
      name: 'Warren Bridges',
      enabled: false,
      type: 'bridges',
    },
    encryptedDnsProxy: {
      id: '',
      name: 'Encrypted DNS Proxy',
      enabled: false,
      type: 'encrypted-dns-proxy',
    },
    domainFronting: {
      id: '',
      enabled: false,
      name: 'Domain fronting',
      type: 'domain-fronting',
    },
    custom: [],
  };
}
