import {
  ApiAccessMethodSettings,
  IRelaySettingsNormal,
  ISettings,
  ObfuscationType,
  Ownership,
} from '../shared/daemon-rpc-types';

export function getDefaultRelaySettingsNormal(): IRelaySettingsNormal {
  return {
    location: 'any',
    providers: [],
    ownership: Ownership.any,
    wireguardConstraints: {
      ipVersion: 'any',
      useMultihop: false,
      entryLocation: 'any',
    },
  };
}

export function getDefaultSettings(): ISettings {
  return {
    allowLan: false,
    autoConnect: false,
    lockdownMode: false,
    showBetaReleases: false,
    splitTunnel: {
      enableExclusions: true,
      appsList: [],
    },
    relaySettings: {
      normal: getDefaultRelaySettingsNormal(),
    },
    tunnelOptions: {
      enableIpv6: false,
      mtu: undefined,
      quantumResistant: true,
      daita: {
        enabled: false,
        directOnly: false,
      },
      dns: {
        state: 'default',
        defaultOptions: {
          blockAds: false,
          blockTrackers: false,
          blockMalware: false,
          blockAdultContent: false,
          blockGambling: false,
          blockSocialMedia: false,
        },
        customOptions: {
          addresses: [],
        },
      },
    },
    obfuscationSettings: {
      selectedObfuscation: ObfuscationType.auto,
      udp2tcpSettings: {
        port: 'any',
      },
      shadowsocksSettings: {
        port: 'any',
      },
      wireGuardPortSettings: {
        port: 'any',
      },
      lwoSettings: {
        port: 'any',
      },
    },
    customLists: [],
    apiAccessMethods: getDefaultApiAccessMethods(),
    relayOverrides: [],
    recents: [],
    // Defaults disabled (standard Mullvad path preserved).
    // The user opts in via the Settings UI or `mullvad warren …`.
    warrenMode: false,
    warrenLocalAccount: false,
    // `undefined` = unset, fallback to Mullvad upstream backend.
    warrenApiUrl: undefined,
    // Default OFF per doctrine `warren_multihop_doctrine_v1`.
    warrenMultiHop: {
      enabled: false,
      entryCountry: '',
      exitCountry: '',
      hpkeEpochRotationMs: 4 * 60 * 60 * 1000,
    },
  };
}

export function getDefaultApiAccessMethods(): ApiAccessMethodSettings {
  // 'id's are UUIDs generated by the daemon when an access method is created,
  // and as such we can't provide a good default value for them.
  return {
    direct: {
      id: '',
      name: 'Direct',
      enabled: true,
      type: 'direct',
    },
    mullvadBridges: {
      id: '',
      name: 'Mullvad Bridges',
      enabled: false,
      type: 'bridges',
    },
    encryptedDnsProxy: {
      id: '',
      name: 'Encrypted DNS Proxy',
      enabled: false,
      type: 'encrypted-dns-proxy',
    },
    domainFronting: {
      id: '',
      enabled: false,
      name: 'Domain fronting',
      type: 'domain-fronting',
    },
    custom: [],
  };
}
