#!/usr/bin/env python3
"""Generate the "WARREN VPN" wordmark as an Android vector drawable.

Android vector drawables cannot rasterise SVG <text>, so the wordmark must be
shipped as filled glyph outlines. This renders the text with a bold sans-serif
(Arial Bold, matching the desktop assets/images/logo-text.svg wordmark) and
writes the result to lib/ui/resource/.../drawable/logo_text.xml.

Run from anywhere: `python3 android/tools/gen_wordmark.py` (needs fonttools).
Regenerate only if the wordmark text or font changes.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

FONT = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
TEXT = "WARREN VPN"
TRACKING = -40  # font units of extra tracking (slightly tight, like desktop letter-spacing -1)
SCALE = 0.1     # font units -> viewport units
DP_HEIGHT = 103.7  # keep parity with the previous wordmark height

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "lib/ui/resource/src/main/res/drawable/logo_text.xml",
)

font = TTFont(FONT)
cmap = font.getBestCmap()
glyphset = font.getGlyphSet()
hmtx = font["hmtx"]

# Lay glyphs left to right in font units (Y up, baseline at 0).
svg = SVGPathPen(glyphset)
bounds = BoundsPen(glyphset)
penx = 0
for ch in TEXT:
    gname = cmap.get(ord(ch), ".notdef")
    if ch != " ":
        t = Transform().translate(penx, 0)
        glyphset[gname].draw(TransformPen(svg, t))
        glyphset[gname].draw(TransformPen(bounds, t))
    penx += hmtx[gname][0] + TRACKING

xMin, yMin, xMax, yMax = bounds.bounds
d = svg.getCommands()

# A <group> maps the Y-up font coords into the Y-down viewport:
#   point (x, y) -> (SCALE*(x - xMin), SCALE*(yMax - y))
vw = round((xMax - xMin) * SCALE, 1)
vh = round((yMax - yMin) * SCALE, 1)
tx = round(-SCALE * xMin, 4)
ty = round(SCALE * yMax, 4)
dp_w = round(DP_HEIGHT * vw / vh, 1)

xml = f'''<!-- Warren VPN wordmark: "WARREN VPN" as filled glyph outlines (Arial Bold),
     mirroring desktop assets/images/logo-text.svg. Paths instead of SVG <text>
     because Android vector drawables do not rasterise text. Generated by
     tools/gen_wordmark.py; regenerate there if the wordmark changes. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="{dp_w}dp"
        android:height="{DP_HEIGHT}dp"
        android:viewportWidth="{vw}"
        android:viewportHeight="{vh}">
    <group android:scaleX="{SCALE}"
           android:scaleY="{-SCALE}"
           android:translateX="{tx}"
           android:translateY="{ty}">
        <path android:fillColor="#FFFFFF"
              android:pathData="{d}" />
    </group>
</vector>
'''
with open(OUT, "w") as f:
    f.write(xml)
print(f"wrote {OUT}  (viewport {vw}x{vh}, {len(d)} path chars)")
