#!/usr/bin/env bash
# Stage the NixOS flake for one release: copy nix/warren-vpn and regenerate
# release.nix so it pins THIS release's .deb by URL and hash.
#
# NixOS ignores .deb, .rpm and .pacman: paths under /opt and /usr do not exist
# there, and nothing would relink the Electron runtime against the store. The
# flake is the distribution channel for that platform, and it is tiny because
# the payload it pins is the .deb the Linux job already published.
#
# The pinned URL is the update host, not the GitHub release: the repository is
# private, so a release asset answers 404 without a token and no user could
# fetch anything.
#
# Usage: ci/stage-nixos-flake.sh <input.deb> <stage-dir> <version> <asset-base-url>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FLAKE_SRC="$REPO_ROOT/nix/warren-vpn"

deb="${1:?usage: stage-nixos-flake.sh <input.deb> <stage-dir> <version> <asset-base-url>}"
stage="${2:?missing stage dir}"
version="${3:?missing version}"
base_url="${4:?missing asset base url}"

for tool in dpkg-deb openssl; do
    command -v "$tool" > /dev/null || {
        echo "::error::$tool is required to stage the NixOS flake" >&2
        exit 1
    }
done

package="$(dpkg-deb -f "$deb" Package)"
case "$package" in
    warren-vpn) suffix="" ;;
    warren-vpn-*) suffix="-${package#warren-vpn-}" ;;
    *)
        echo "::error::unexpected package name '$package' (expected warren-vpn[-env])" >&2
        exit 1
        ;;
esac
channel="${suffix:+${suffix#-}}"
channel="${channel:-prod}"

# The product name is the single directory under /opt, and it is what the
# install phase moves into the store.
product_name="$(dpkg-deb -c "$deb" | sed -n 's|.* \./opt/\([^/]*\)/$|\1|p' | head -1)"
[ -n "$product_name" ] || {
    echo "::error::no product directory under /opt in $deb" >&2
    exit 1
}

# fetchurl wants the digest in SRI form (base64), which openssl produces
# directly from the file.
sha_sri="sha256-$(openssl dgst -binary -sha256 "$deb" | base64 | tr -d '\n')"

rm -rf "$stage"
mkdir -p "$stage"
cp "$FLAKE_SRC/flake.nix" "$FLAKE_SRC/package.nix" "$FLAKE_SRC/module.nix" \
    "$FLAKE_SRC/README.md" "$stage/"

cat > "$stage/release.nix" << EOF
# Generated by ci/stage-nixos-flake.sh for this release. Do not edit: the
# pinned hash is what makes the download verifiable.
{
  version = "${version}";
  channel = "${channel}";
  suffix = "${suffix}";
  productName = "${product_name}";
  packageName = "${package}";
  url = "${base_url%/}/$(basename "$deb")";
  hash = "${sha_sri}";
}
EOF

echo "Staged the NixOS flake in $stage"
sed -n '3,$p' "$stage/release.nix"
