export enum RoutePath {
  launch = '/',
  login = '/login',
  deviceRevoked = '/login/device-revoked',
  main = '/main',
  redeemVoucher = '/main/voucher/redeem',
  voucherSuccess = '/main/voucher/success/:newExpiry/:secondsAdded',
  expired = '/main/expired',
  timeAdded = '/main/time-added',
  setupFinished = '/main/setup-finished',
  settings = '/settings',
  selectLanguage = '/settings/language',
  account = '/account',
  withdrawContract = '/account/withdraw',
  keys = '/account/keys',
  restoreKeys = '/account/keys/restore',
  userInterfaceSettings = '/settings/interface',
  multihopSettings = '/settings/multihop',
  warrenMultiHopSettings = '/settings/warren-multi-hop',
  // Warren NAT-PMP port-forwarding (M4.H.F differentiator vs Mullvad
  // / IVPN abandon 2023). View opens from the settings home view.
  portForwardingSettings = '/settings/port-forwarding',
  vpnSettings = '/settings/vpn',
  daitaSettings = '/settings/daita',
  udpOverTcp = '/settings/advanced/wireguard/udp-over-tcp',
  shadowsocks = '/settings/advanced/shadowsocks',
  splitTunneling = '/settings/split-tunneling',
  apiAccessMethods = '/settings/api-access-methods',
  settingsImport = '/settings/settings-import',
  settingsTextImport = '/settings/settings-import/text-import',
  editApiAccessMethods = '/settings/api-access-methods/edit/:id?',
  support = '/settings/support',
  problemReport = '/settings/support/problem-report',
  debug = '/settings/debug',
  selectLocation = '/select-location',
  filter = '/select-location/filter',
  appInfo = '/settings/app-info',
  changelog = '/settings/changelog',
  appUpgrade = '/settings/app-upgrade',
  antiCensorship = '/settings/advanced/anti-censorship',
  lwo = '/settings/advanced/lwo',
  // M5.B.3 onboarding wizard (first-launch welcome + wallet
  // generate/import + subscription pointer + privacy preferences +
  // done). Re-triggerable from Settings ("Replay onboarding"). Uses
  // a route-based flow (vs modal overlay) so demo links and support
  // can deep-link a user to a specific step.
  onboardingWelcome = '/onboarding',
  onboardingWallet = '/onboarding/wallet',
  onboardingSubscription = '/onboarding/subscription',
  onboardingPreferences = '/onboarding/preferences',
  onboardingDone = '/onboarding/done',
}
