#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# Warren VPN, dev sudo NOPASSWD setup (macOS + Linux)
#
# Installs a scoped /etc/sudoers.d drop-in so the whole Warren dev workflow,
# including privileged datapath tests, runs without per-command password
# prompts:
#   - warren-dev.sh daemon        : warren-daemon as root + DNS snapshot/kill
#   - cargo-test-nofw.sh          : toggles the macOS application firewall
#   - warren-client --use-tun     : datapath repro/bench (creates a utun/tun,
#                                   needs root; warren-core sibling binary)
#   - host-route tweaks           : route a single test IP through a side tun,
#                                   pinned to `-host` routes so the DEFAULT
#                                   route can never be touched by this grant
#
# Every rule pins an absolute binary (and, where it matters, its leading
# arguments): this grants NO general privilege escalation, and the route
# rules are pinned to host routes so they cannot redirect default traffic.
# The generated file is validated with `visudo -c` BEFORE install, so a typo
# can never lock you out of sudo.
#
# Re-runnable and machine-portable: the dev user and binary paths are derived
# at run time (no hardcoded /Users/<name>). On Linux it ALSO tries to setcap
# the client binary (cap_net_admin,cap_net_raw) so `--use-tun` needs no sudo
# at all; the sudoers rules remain as the portable fallback (and for macOS,
# which has no capability model).
#
# Usage:  ./scripts/dev/setup-sudo-nopasswd.sh           # install
#         ./scripts/dev/setup-sudo-nopasswd.sh --remove  # uninstall
# ─────────────────────────────────────────────────────────────────────

SUDOERS_FILE=/etc/sudoers.d/warren-dev
OS=$(uname -s)

die() { echo "error: $*" >&2; exit 1; }

# Target the human who runs the dev tools, even when invoked via sudo.
DEV_USER="${SUDO_USER:-$(id -un)}"

if [[ "${1:-}" == "--remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  echo "Removed $SUDOERS_FILE."
  exit 0
fi

# warren-app repo root, derived from this script's own location
# (<repo>/scripts/dev/<this>), so it works from any checkout on any host.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd -P)
WORKSPACE=$(cd "$REPO_ROOT/.." && pwd -P)
DAEMON_REL="$REPO_ROOT/target/release/warren-daemon"
DAEMON_DBG="$REPO_ROOT/target/debug/warren-daemon"
# warren-client lives in the warren-core sibling (datapath repro/bench binary).
CLIENT_REL="$WORKSPACE/warren-core/target/release/warren-client"
CLIENT_DBG="$WORKSPACE/warren-core/target/debug/warren-client"

[[ -f "$SCRIPT_DIR/warren-dev.sh" ]] || \
  die "expected to live in <warren-app>/scripts/dev/ next to warren-dev.sh (got $SCRIPT_DIR)."

# Build the drop-in in a temp file first; validate; then install atomically.
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

if [[ "$OS" == "Darwin" ]]; then
  GRP=wheel
  cat > "$tmp" <<EOF
# Warren dev workflow, scoped NOPASSWD (macOS). Generated by
# scripts/dev/setup-sudo-nopasswd.sh; re-run that script to regenerate.
# Every rule pins an absolute binary: no general privilege escalation.

# cargo-test-nofw.sh : toggle the macOS application firewall around tests.
Cmnd_Alias WARREN_FW = /usr/libexec/ApplicationFirewall/socketfilterfw *

# warren-dev.sh : DNS snapshot/restore + resolver cache flush.
Cmnd_Alias WARREN_DNS = /usr/sbin/networksetup -setdnsservers *, /usr/bin/dscacheutil -flushcache, /usr/bin/killall -HUP mDNSResponder

# warren-dev.sh : the daemon runs as root, so it is killed as root.
Cmnd_Alias WARREN_KILL = /bin/kill -TERM *, /bin/kill -KILL *

# warren-dev.sh ensure_sudo : the \`sudo -n true\` pre-auth probe.
Cmnd_Alias WARREN_PREAUTH = /usr/bin/true

# warren-dev.sh : run the freshly built daemon as root (release or debug).
Cmnd_Alias WARREN_DAEMON = /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_REL *, /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_DBG *

# warren-client --use-tun : datapath repro/bench (creates a utun; needs root).
Cmnd_Alias WARREN_CLIENT = $CLIENT_REL *, $CLIENT_REL, $CLIENT_DBG *, $CLIENT_DBG

# Host-route tweaks for side-tun tests: pinned to \`-host\` so the DEFAULT
# route can never be changed through this grant (no leak, no self-lockout).
Cmnd_Alias WARREN_ROUTE = /sbin/route -n add -host *, /sbin/route add -host *, /sbin/route -n delete -host *, /sbin/route delete -host *, /sbin/route -n get *

$DEV_USER ALL=(root) NOPASSWD: WARREN_FW, WARREN_DNS, WARREN_KILL, WARREN_PREAUTH, WARREN_CLIENT, WARREN_ROUTE
$DEV_USER ALL=(root) NOPASSWD: SETENV: WARREN_DAEMON
EOF
else
  # Linux (and other unices with /etc/sudoers.d).
  GRP=root
  cat > "$tmp" <<EOF
# Warren dev workflow, scoped NOPASSWD (Linux). Generated by
# scripts/dev/setup-sudo-nopasswd.sh; re-run that script to regenerate.
# Every rule pins an absolute binary: no general privilege escalation.

Cmnd_Alias WARREN_KILL = /bin/kill -TERM *, /bin/kill -KILL *, /usr/bin/kill -TERM *, /usr/bin/kill -KILL *
Cmnd_Alias WARREN_PREAUTH = /bin/true, /usr/bin/true

# warren-daemon as root (release or debug).
Cmnd_Alias WARREN_DAEMON = /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_REL *, /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_DBG *

# warren-client --use-tun : datapath repro/bench (creates /dev/net/tun; needs
# root unless the binary is setcap'd, which this script also attempts below).
Cmnd_Alias WARREN_CLIENT = $CLIENT_REL *, $CLIENT_REL, $CLIENT_DBG *, $CLIENT_DBG

# Host-route tweaks for side-tun tests, pinned to a single destination so the
# DEFAULT route can never be redirected through this grant.
Cmnd_Alias WARREN_ROUTE = /sbin/ip route add * dev *, /usr/sbin/ip route add * dev *, /bin/ip route add * dev *, /usr/bin/ip route add * dev *, /sbin/ip route del * dev *, /usr/sbin/ip route del * dev *, /bin/ip route del * dev *, /usr/bin/ip route del * dev *

$DEV_USER ALL=(root) NOPASSWD: WARREN_KILL, WARREN_PREAUTH, WARREN_CLIENT, WARREN_ROUTE
$DEV_USER ALL=(root) NOPASSWD: SETENV: WARREN_DAEMON
EOF
fi

echo "Validating generated sudoers (you may be prompted for your password once)…"
sudo visudo -c -f "$tmp" >/dev/null || die "generated sudoers failed validation; nothing installed."

sudo install -m 0440 -o root -g "$GRP" "$tmp" "$SUDOERS_FILE" 2>/dev/null \
  || sudo install -m 0440 -o root -g root "$tmp" "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" >/dev/null || die "post-install validation failed (unexpected)."

echo "Installed $SUDOERS_FILE for user '$DEV_USER' ($OS)."
echo "  daemon (release): $DAEMON_REL"
echo "  daemon (debug):   $DAEMON_DBG"
echo "  client (debug):   $CLIENT_DBG"

# Linux bonus: file-capabilities so --use-tun needs no sudo at all. Best
# effort: a missing setcap or a noexec mount just leaves the sudoers fallback.
if [[ "$OS" != "Darwin" ]] && command -v setcap >/dev/null 2>&1; then
  for b in "$CLIENT_DBG" "$CLIENT_REL"; do
    [[ -f "$b" ]] && sudo setcap 'cap_net_admin,cap_net_raw+eip' "$b" 2>/dev/null \
      && echo "  setcap cap_net_admin,cap_net_raw on $(basename "$b") (no sudo needed for --use-tun; re-run after each rebuild)"
  done
fi

# Smoke test: must not prompt.
if sudo -n true 2>/dev/null; then
  echo "NOPASSWD active: warren-dev.sh daemon, cargo-test-nofw.sh, and"
  echo "'sudo -n $CLIENT_DBG --use-tun ...' will no longer prompt for a password."
else
  die "smoke test still prompts; inspect $SUDOERS_FILE."
fi
