#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# Warren VPN — dev sudo NOPASSWD setup (macOS)
#
# Installs a scoped /etc/sudoers.d drop-in so the Warren dev workflow runs
# without per-command password prompts:
#   - scripts/dev/warren-dev.sh daemon  (runs warren-daemon as root, DNS
#     snapshot/restore, kills the root daemon)
#   - warren-core/scripts/dev/cargo-test-nofw.sh  (toggles the macOS
#     application firewall around tests)
#
# Every rule pins an absolute binary (and, where it matters, its leading
# arguments): this grants NO general privilege escalation. The generated
# file is validated with `visudo -c` BEFORE being installed, so a typo can
# never lock you out of sudo.
#
# Re-runnable and machine-portable: the dev user and the warren-daemon
# path are derived at run time (no hardcoded /Users/<name>).
#
# Usage:  ./scripts/dev/setup-sudo-nopasswd.sh           # install
#         ./scripts/dev/setup-sudo-nopasswd.sh --remove  # uninstall
# ─────────────────────────────────────────────────────────────────────

SUDOERS_FILE=/etc/sudoers.d/warren-dev

die() { echo "error: $*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "macOS only (uses socketfilterfw / networksetup)."

# Target the human who runs the dev tools, even when invoked via sudo.
DEV_USER="${SUDO_USER:-$(id -un)}"

if [[ "${1:-}" == "--remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  echo "Removed $SUDOERS_FILE."
  exit 0
fi

# warren-app repo root, derived from this script's own location
# (<repo>/scripts/dev/<this>), so it works from any checkout on any host.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd -P)
DAEMON_REL="$REPO_ROOT/target/release/warren-daemon"
DAEMON_DBG="$REPO_ROOT/target/debug/warren-daemon"

[[ -f "$SCRIPT_DIR/warren-dev.sh" ]] || \
  die "expected to live in <warren-app>/scripts/dev/ next to warren-dev.sh (got $SCRIPT_DIR)."

# Build the drop-in in a temp file first; validate; then install atomically.
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" <<EOF
# Warren dev workflow — scoped NOPASSWD. Generated by
# scripts/dev/setup-sudo-nopasswd.sh; re-run that script to regenerate.
# Every rule pins an absolute binary: no general privilege escalation.

# cargo-test-nofw.sh : toggle the macOS application firewall around tests.
Cmnd_Alias WARREN_FW = /usr/libexec/ApplicationFirewall/socketfilterfw *

# warren-dev.sh : DNS snapshot/restore + resolver cache flush.
Cmnd_Alias WARREN_DNS = /usr/sbin/networksetup -setdnsservers *, /usr/bin/dscacheutil -flushcache, /usr/bin/killall -HUP mDNSResponder

# warren-dev.sh : the daemon runs as root, so it is killed as root.
Cmnd_Alias WARREN_KILL = /bin/kill -TERM *, /bin/kill -KILL *

# warren-dev.sh ensure_sudo : the \`sudo -n true\` pre-auth probe.
Cmnd_Alias WARREN_PREAUTH = /usr/bin/true

# warren-dev.sh : run the freshly built daemon as root (release or debug).
# Pinned to the exact env var + binary path; the trailing wildcard covers
# only the daemon's own flags. \`env\` cannot be coerced into a root shell
# because its first two arguments are fixed.
Cmnd_Alias WARREN_DAEMON = /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_REL *, /usr/bin/env WARREN_USE_PLAINTEXT_STORAGE=1 $DAEMON_DBG *

$DEV_USER ALL=(root) NOPASSWD: WARREN_FW, WARREN_DNS, WARREN_KILL, WARREN_PREAUTH
$DEV_USER ALL=(root) NOPASSWD: SETENV: WARREN_DAEMON
EOF

echo "Validating generated sudoers (you may be prompted for your password once)…"
sudo visudo -c -f "$tmp" >/dev/null || die "generated sudoers failed validation; nothing installed."

sudo install -m 0440 -o root -g wheel "$tmp" "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" >/dev/null || die "post-install validation failed (unexpected)."

echo "Installed $SUDOERS_FILE for user '$DEV_USER'."
echo "  daemon (release): $DAEMON_REL"
echo "  daemon (debug):   $DAEMON_DBG"

# Smoke test: must not prompt.
if sudo -n /usr/bin/true 2>/dev/null \
   && sudo -n /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate >/dev/null 2>&1; then
  echo "NOPASSWD active — warren-dev.sh daemon and cargo-test-nofw.sh will not prompt."
else
  die "smoke test still prompts; inspect $SUDOERS_FILE."
fi
